[tasks.test]
# this needs the crates 'nextest' and 'cargo-llvm-cov' installed locally
command = "cargo"
args = ["llvm-cov", "nextest", "--no-fail-fast"]

[tasks.test-html]
command = "cargo"
args = ["llvm-cov", "nextest", "--no-fail-fast", "--html"]
